<?php 
return array(
		Category::TYPE_ITEST=>array(
			'form'=>'_form',
			'max_rank'=>1,
			'code'=>'itest',
			'class'=>'ITest',
			'label'=>'Language'	
		),
		Category::TYPE_NEWS=>array(
			'form'=>'_form',
			'max_rank'=>3,
			'code'=>'news',
			'class'=>'News',
			'label'=>'News'	
		),
		Category::TYPE_EXAM=>array(
			'form'=>'_form',
			'max_rank'=>1,
			'code'=>'exam',
			'class'=>'Exam',
			'label'=>'Office'	
		),
	);