<?php
return array(
	'role'=>array(
		'manager_operation'=>'Manager Operations',
		'manager_task'=>'Manager Task',
		'manager_role'=>'Manager Role'
	),
	'menu'=>array(
		'manager'=>'Manager',		
	),
	'language'=>array(
		'create'=>'Create',
		'edit'=>'Edit',
		'delete'=>'Delete',
		'import'=>'Import',
		'export'=>'Export'
	),
	'setting'=>array(
		'index'=>'Manager'
	),
	'image'=>array(
		'list'=>'List',
		'clear_image'=>'Clear'
	),
	'user'=>array(
		'index'=>'Manager',
		'create'=>'Create'
	),
	'languageSkill'=>array(
		'index'=>'Manager',
		'create'=>'Create'
	),
	'knowledgeSkill'=>array(
		'index'=>'Manager',
		'create'=>'Create'
	),
	'markingUpSkill'=>array(
		'index'=>'Manager',
		'create'=>'Create'
	),
	'codingSkill'=>array(
		'index'=>'Manager',
		'create'=>'Create'
	),
	'exam'=>array(
		'index'=>'Manager',
		'create'=>'Create',
		'list'=>'List'
	),
	'result'=>array(
		'index'=>'Manager',
	),
	'system'=>array(
		'language'=>'Language',
		'office'=>'Office',		
	),
	'course'=>array(
		'index'=>'Manager',
		'create'=>'Create'
	)
);